runtime: nodejs
vm: true

env_variables:
  GCLOUD_PROJECT: your-appengine-project
  API_KEY: Your-API-Key

manual_scaling:
  instances: 1

#automatic_scaling:
#  min_num_instances: 1
#  max_num_instances: 10
#  cool_down_period_sec: 120 # default value
#  cpu_utilization:
#    target_utilization: 0.5

handlers:
- url: /.*
  script: IGNORED
  # Always use https
  secure: always

# Temporary setting to keep gcloud from uploading node_modules
skip_files:
- ^node_modules$
